// WARNING: Here be Dragons
// This file is generated by Creer, do not modify it
// It basically sets up all the classes, interfaces, types, and what-not that
// we need for TypeScript to know the base classes, while allowing for minimal
// code for developers to be forced to fill out.

/* eslint-disable @typescript-eslint/no-empty-interface */

// base game classes
import {
    BaseAI,
    BaseGame,
    BaseGameManager,
    BaseGameObject,
    BaseGameObjectFactory,
    BaseGameSettingsManager,
    BasePlayer,
    makeNamespace,
} from "~/core/game";

// mixins
import { SuperGridPlayer, mixSuperGrid } from "~/core/game/mixins";

/**
 * The interface that the Player for the ConnectFour game
 * must implement from mixed in game logic.
 */
export interface BaseConnectFourPlayer extends BasePlayer, SuperGridPlayer {}

const base0 = {
    AI: BaseAI,
    Game: BaseGame,
    GameManager: BaseGameManager,
    GameObject: BaseGameObject,
    GameSettings: BaseGameSettingsManager,
};

const base1 = mixSuperGrid(base0);

const mixed = base1;

/** The base AI class for the ConnectFour game will mixin logic. */
class BaseConnectFourAI extends mixed.AI {}

/** The base Game class for the ConnectFour game will mixin logic. */
class BaseConnectFourGame extends mixed.Game {}

/** The base GameManager class for the ConnectFour game will mixin logic. */
class BaseConnectFourGameManager extends mixed.GameManager {}

/** The base GameObject class for the ConnectFour game will mixin logic. */
class BaseConnectFourGameObject extends mixed.GameObject {}

/** The base GameSettings class for the ConnectFour game will mixin logic. */
class BaseConnectFourGameSettings extends mixed.GameSettings {}

/** The Base classes that game classes build off of. */
export const BaseClasses = {
    AI: BaseConnectFourAI,
    Game: BaseConnectFourGame,
    GameManager: BaseConnectFourGameManager,
    GameObject: BaseConnectFourGameObject,
    GameSettings: BaseConnectFourGameSettings,
};

// Now all the base classes are created;
// so we can start importing/exporting the classes that need them.

/** All the possible properties for GameObject instances. */
export interface GameObjectProperties {}

/** All the possible properties for Player instances. */
export interface PlayerProperties {
    /**
     * What type of client this is, e.g. 'Python', 'JavaScript', or some other
     * language. For potential data mining purposes.
     */
    clientType?: string;

    /**
     * The color (side) of this player. Either 'red' or 'yellow', with
     * the 'yellow' player having the first move.
     */
    color?: "r" | "y";

    /**
     * If the player lost the game or not.
     */
    lost?: boolean;

    /**
     * The name of the player.
     */
    name?: string;

    /**
     * The reason why the player lost the game.
     */
    reasonLost?: string;

    /**
     * The reason why the player won the game.
     */
    reasonWon?: string;

    /**
     * The amount of time (in ns) remaining for this AI to send commands.
     */
    timeRemaining?: number;

    /**
     * If the player won the game or not.
     */
    won?: boolean;
}

/**
 * The default args passed to a constructor function for class
 * instances of GameObject.
 */
export type GameObjectConstructorArgs<
    T extends Record<string, unknown> = Record<string, unknown>
> = Readonly<GameObjectProperties & T>;

/**
 * The default args passed to a constructor function for class
 * instances of Player.
 */
export type PlayerConstructorArgs<
    T extends Record<string, unknown> = Record<string, unknown>
> = Readonly<BaseConnectFourPlayer & PlayerProperties & T>;

export * from "./game-object";
export * from "./player";
export * from "./game";
export * from "./game-manager";
export * from "./ai";

import { GameObject } from "./game-object";
import { Player } from "./player";

import { AI } from "./ai";
import { ConnectFourGame } from "./game";
import { ConnectFourGameManager } from "./game-manager";
import { ConnectFourGameSettingsManager } from "./game-settings";

/**
 * The factory that **must** be used to create any game objects in
 * the ConnectFour game.
 */
export class ConnectFourGameObjectFactory extends BaseGameObjectFactory {}

/**
 * The shared namespace for ConnectFour that is used to
 * initialize each game instance.
 */
export const Namespace = makeNamespace({
    AI,
    Game: ConnectFourGame,
    GameManager: ConnectFourGameManager,
    GameObjectFactory: ConnectFourGameObjectFactory,
    GameSettingsManager: ConnectFourGameSettingsManager,
    Player,

    // These are generated metadata that allow delta-merging values from
    // clients.
    // They are never intended to be directly interfaced with outside of the
    // Cerveau core developers.
    gameName: "ConnectFour",
    gameSettingsManager: new ConnectFourGameSettingsManager(),
    gameObjectsSchema: {
        AI: {
            attributes: {},
            functions: {
                makeMove: {
                    args: [],
                    returns: {
                        typeName: "string",
                    },
                },
            },
        },
        Game: {
            attributes: {
                cols: {
                    typeName: "int",
                },
                gameObjects: {
                    typeName: "dictionary",
                    keyType: {
                        typeName: "string",
                    },
                    valueType: {
                        typeName: "gameObject",
                        gameObjectClass: GameObject,
                        nullable: false,
                    },
                },
                players: {
                    typeName: "list",
                    valueType: {
                        typeName: "gameObject",
                        gameObjectClass: Player,
                        nullable: false,
                    },
                },
                repString: {
                    typeName: "string",
                },
                rows: {
                    typeName: "int",
                },
                session: {
                    typeName: "string",
                },
            },
            functions: {},
        },
        GameObject: {
            attributes: {
                gameObjectName: {
                    typeName: "string",
                },
                id: {
                    typeName: "string",
                },
                logs: {
                    typeName: "list",
                    valueType: {
                        typeName: "string",
                    },
                },
            },
            functions: {
                log: {
                    args: [
                        {
                            argName: "message",
                            typeName: "string",
                        },
                    ],
                    returns: {
                        typeName: "void",
                    },
                },
            },
        },
        Player: {
            parentClassName: "GameObject",
            attributes: {
                clientType: {
                    typeName: "string",
                },
                color: {
                    typeName: "string",
                    defaultValue: "r",
                    literals: ["r", "y"],
                },
                lost: {
                    typeName: "boolean",
                },
                name: {
                    typeName: "string",
                },
                reasonLost: {
                    typeName: "string",
                },
                reasonWon: {
                    typeName: "string",
                },
                timeRemaining: {
                    typeName: "float",
                },
                won: {
                    typeName: "boolean",
                },
            },
            functions: {},
        },
    },
    gameVersion:
        "2ef5b01e54f1c3bbda4b90c76968cc2c28032baac1a6e546a1d005448e2abfde",
});
